Repository acm-ucr/cvdsa-uoft-website, pull requests merged in 2025-03, with the labels that each got.

#104 centered error404
  src/components/error/NotFound.tsx
Labels: ready for review

#105 Cwu423/data files
  src/data/developments.ts
  src/data/events.ts
Labels: ready for review

#112 add 404 text
  src/app/not-found.tsx
  src/components/home/Landing.tsx
Labels: ready for review, changes requested

#114 Cwu423/animate social blurbs
  src/components/socials/ContactCard.tsx
  src/components/socials/Contacts.tsx
Labels: ready for review

#115 Animated the about us title and the blurb
  src/components/home/AboutUsBlurb.tsx
Labels: ready for review

#68 Jisu calendar
  components.json
  package-lock.json
  package.json
  src/app/events/page.tsx
  src/app/globals.css
  src/components/events/CalendarCall.tsx
  src/components/events/CalendarDay.tsx
  src/components/events/CalendarEventPopover.tsx
  src/components/events/CalendarTop.tsx
  src/components/events/PastEvent.tsx
  src/components/events/PastEvents.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/popover.tsx
  src/data/eventinfo.ts
  src/lib/utils.ts
  tailwind.config.ts
Labels: do not merge, help wanted
